### ISSUE TITLE
Compilation of tag 0.2 or master on Mac OS broken

### ISSUE THREAD

**Issue by jlingema** [HEP-FCC/fcc-physics#21]
Compiling against FCC-EDM v0.5 on MacOS, does not work:

```
.../include/TH1.h:68:10: warning: non-portable path to file
      '<Float.h>'; specified path differs in case from file name on disk
      [-Wnonportable-include-path]
#include <float.h>
```
This is due to the conflicting name of the datatype `Float` [in fcc-edm](https://github.com/HEP-FCC/fcc-edm/blob/master/edm.yaml#L57) and will be fixed once PR HEP-FCC/fcc-edm#39 is merged. Unfortunately, it has some implications and we decided to wait until merging it. In the meantime one has to use Colin's branch when compiling on the Mac.

**Comment by cbernet** [comment]
Hi @jlingema what's the status about this? Can we now do this change?

**Comment by jlingema** [comment]
Yes, I think the PR can now be merged. Or do you have objections @clementhelsens?

**Comment by clementhelsens** [comment]
No objections.
What’s the timescale of a new FCCSW tag then :)
Le 20 juin 2017 à 17:06, Joschka Lingemann <notifications@github.com<mailto:notifications@github.com>> a écrit :


Yes, I think the PR can now be merged. Or do you have objections @clementhelsens<https://github.com/clementhelsens>?
